# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Tour
    url: tour
    weight: 10
  - name: Исследования
    url: research
    weight: 15
  - name: Новости #News
    url: post
    weight: 20
  - name: Команда  #People
    url: people
    weight: 30
  - name: События # Events
    url: event
    weight: 40
  - name: Публикации  # Publications
    url: publication
    weight: 50

  - name: Студентам  # Publications
    url: for-students
    weight: 60  
  - name: Учебные курсы  
    parent: Студентам
    url: for-students/courses
    weight: 1
  - name: Курсовые работы  
    parent: Студентам
    url: for-students/my-first-research
    weight: 2
    
  - name: Контакты # Contact
    url: contact
    weight: 70
